export const sagaActions = {
  FETCH_TICKETS_SAGA: 'FETCH_TICKETS_SAGA',
  FETCH_CUSTOMERS_SAGA: 'FETCH_CUSTOMERS_SAGA',
  LOGIN_USER_SAGA: 'LOGIN_USER_SAGA',
  DELETE_TICKET_SAGA: 'DELETE_TICKET_SAGA',
  DELETE_CUSTOMER_SAGA: 'DELETE_TICKET_SAGA',
  ADD_CUSTOMER_SAGA: 'ADD_CUSTOMER_SAGA',
  EDIT_CUSTOMER_SAGA: 'EDIT_CUSTOMER_SAGA',
  ADD_TICKET_SAGA: 'ADD_TICKET_SAGA',
  EDIT_TICKET_SAGA: 'EDIT_TICKET_SAGA',
};
