export const sagaActions = {
  FETCH_TICKETS_SAGA: 'FETCH_TICKETS_SAGA',
  FETCH_CUSTOMERS_SAGA: 'FETCH_CUSTOMERS_SAGA',
  LOGIN_USER_SAGA: 'LOGIN_USER_SAGA',
  DELETE_TICKET_SAGA: 'DELETE_TICKET_SAGA',
  DELETE_CUSTOMER_SAGA: 'DELETE_TICKET_SAGA',
};
